services:
  chain-pass-server:
    image: chain-pass-server
    container_name: chain-pass-server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - 8080:8080
      - 8888:8888/udp
    env_file: ./server/.env
    volumes:
      - ./server/db:/app/db